/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame_ATM.java
 *
 * Created on 11/Nov/2010, 15:26:53
 */

package gui_atm;

import gestores.GestorFilmes;
import gestores_atm.GestorUtilizadores;
import java.awt.Component;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import outros.Filme;
import outros.OurListModel;
import outros.Utils;

/**
 *
 * @author Daniela
 */
public class Frame_ATM  extends JFrame{
    
    /**
    * @param args the command line arguments
    */
    GestorUtilizadores gerir_users = new GestorUtilizadores();
    GestorFilmes gestorFilmes = new GestorFilmes();
    Filme [] filmesPesquisados;

    public static void main(String args[]) {
        
                System.out.println("Here");
                new Frame_ATM().setVisible(true);
                //adds the panels to the interface
                
                Scanner sc = new Scanner(System.in);
                sc.next();
         
    }
    
    
    
    /** Creates new form Frame_ATM */
    public Frame_ATM() {
        //initializes all the componentes needed in the GUI
       
        setSize(800, 600);
	setTitle("ATM");
	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       
        initComponents();
        add(mainPanel);
        mainPanel.setLayout(null);
        mainPanel.setVisible(true);
        init();
        System.out.println("WHY");

    }

      public void init(){

        mainPanel.setLayout(null);
        mainPanel.add(jDadosPanel);
        mainPanel.add(jPanel3);
        mainPanel.add(jEntregaPanel);
        mainPanel.add(jLoginPanel);
        mainPanel.add(jHistoricoPanel);
        mainPanel.add(jMenuPanel);
        mainPanel.add(jResultadosPanel);
        mainPanel.add(jPesquisarPanel);

        //Set panel's visibility
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(true);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
        //Alignes the panels in the frame

        jDadosPanel.setBounds(0, -1, 800, 600);
        jPanel3.setBounds(0, -1, 800, 600);
        jEntregaPanel.setBounds(0, -1, 800, 600);
        jLoginPanel.setBounds(0, -1, 800, 600);
        jHistoricoPanel.setBounds(0, -1, 800, 600);
        jMenuPanel.setBounds(0, -1, 800, 600);
        jResultadosPanel.setBounds(0, -1, 800, 600);
        jPesquisarPanel.setBounds(0, -1, 800, 600);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuPanel = new javax.swing.JPanel();
        jPesquisarButton = new javax.swing.JToggleButton();
        jEntregarButton = new javax.swing.JToggleButton();
        jHistoricoButton = new javax.swing.JToggleButton();
        jSairButton = new javax.swing.JButton();
        jDadosButton = new javax.swing.JToggleButton();
        jAjudaButton = new javax.swing.JButton();
        jPesquisarPanel = new javax.swing.JPanel();
        jSairButton2 = new javax.swing.JButton();
        jAjudaButton2 = new javax.swing.JButton();
        jVoltarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSearchButton = new javax.swing.JToggleButton();
        jSpinner4 = new javax.swing.JSpinner();
        jTextField17 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel41 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jResultadosPanel = new javax.swing.JPanel();
        jSairButton3 = new javax.swing.JButton();
        jAjudaButton3 = new javax.swing.JButton();
        jVoltarPesquisaButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel22 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jHistoricoPanel = new javax.swing.JPanel();
        jSairButton4 = new javax.swing.JButton();
        jVoltarButton4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLoginPanel = new javax.swing.JPanel();
        jLoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jUsernameField = new javax.swing.JTextField();
        jUsernameField.setText("Insert Username Here");
        jLabel5 = new javax.swing.JLabel();
        jEntregaPanel = new javax.swing.JPanel();
        jSairButton5 = new javax.swing.JButton();
        jAjudaButton5 = new javax.swing.JButton();
        jMenuButton5 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPagarButton = new javax.swing.JButton();
        jDadosPanel = new javax.swing.JPanel();
        jSairButton6 = new javax.swing.JButton();
        jVoltarButton6 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        mainPanel = new javax.swing.JPanel();

        jPesquisarButton.setText("Pesquisar Filmes");
        jPesquisarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisarButtonActionPerformed(evt);
            }
        });

        jEntregarButton.setText("Entregar Filme");
        jEntregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEntregarButtonActionPerformed(evt);
            }
        });

        jHistoricoButton.setText("Ver Histórico");
        jHistoricoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHistoricoButtonActionPerformed(evt);
            }
        });

        jSairButton.setText("SAIR");
        jSairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairButtonActionPerformed(evt);
            }
        });

        jDadosButton.setText("Ver Dados Pessoais");
        jDadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDadosButtonActionPerformed(evt);
            }
        });

        jAjudaButton.setText("AJUDA");
        jAjudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAjudaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jMenuPanelLayout = new javax.swing.GroupLayout(jMenuPanel);
        jMenuPanel.setLayout(jMenuPanelLayout);
        jMenuPanelLayout.setHorizontalGroup(
            jMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jAjudaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHistoricoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPesquisarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEntregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(718, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMenuPanelLayout.createSequentialGroup()
                .addContainerGap(632, Short.MAX_VALUE)
                .addComponent(jSairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(554, 554, 554))
        );
        jMenuPanelLayout.setVerticalGroup(
            jMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuPanelLayout.createSequentialGroup()
                .addGroup(jMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMenuPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPesquisarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jEntregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jHistoricoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jMenuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jAjudaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPesquisarPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        jPesquisarPanel.setMinimumSize(new java.awt.Dimension(800, 600));

        jSairButton2.setText("SAIR");
        jSairButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairButton2ActionPerformed(evt);
            }
        });

        jAjudaButton2.setText("AJUDA");
        jAjudaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAjudaButton2ActionPerformed(evt);
            }
        });

        jVoltarButton.setText("Voltar");
        jVoltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel3.setText("Pesquisar Filme");

        jLabel4.setText("Título:");

        jLabel6.setText("Género:");

        jLabel7.setText("Ano:");

        jLabel8.setText("Realizador:");

        jLabel9.setText("Produtor:");

        jLabel11.setText("Between");

        jLabel12.setText("And");

        jLabel10.setText("IMDB RATING: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSearchButton.setText("SEARCH");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jTextField17.setText("jTextField17");

        javax.swing.GroupLayout jPesquisarPanelLayout = new javax.swing.GroupLayout(jPesquisarPanel);
        jPesquisarPanel.setLayout(jPesquisarPanelLayout);
        jPesquisarPanelLayout.setHorizontalGroup(
            jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPesquisarPanelLayout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel3)
                .addContainerGap(390, Short.MAX_VALUE))
            .addGroup(jPesquisarPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPesquisarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPesquisarPanelLayout.createSequentialGroup()
                        .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jVoltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jSairButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPesquisarPanelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPesquisarPanelLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPesquisarPanelLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPesquisarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(152, 152, 152))
            .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPesquisarPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jAjudaButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(775, Short.MAX_VALUE)))
        );
        jPesquisarPanelLayout.setVerticalGroup(
            jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPesquisarPanelLayout.createSequentialGroup()
                .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPesquisarPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(jPesquisarPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSairButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVoltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(jPesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPesquisarPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jAjudaButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(530, Short.MAX_VALUE)))
        );

        jLabel38.setText("Título:");

        jLabel39.setText("Preço:");

        jLabel40.setText("Data Limite de Entrega:");

        jLabel41.setText("Aguarde enquanto o seu filme é entregue.");

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setText("jFormattedTextField1");

        jTextField20.setEditable(false);
        jTextField20.setText("jTextField20");

        jTextField21.setEditable(false);
        jTextField21.setText("jTextField21");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField1)
                            .addComponent(jTextField20)
                            .addComponent(jTextField21)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel41)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel41)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jSairButton3.setText("SAIR");
        jSairButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairButton3ActionPerformed(evt);
            }
        });

        jAjudaButton3.setText("AJUDA");
        jAjudaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAjudaButton3ActionPerformed(evt);
            }
        });

        jVoltarPesquisaButton.setText("Voltar");
        jVoltarPesquisaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarPesquisaButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel13.setText("Resultados Filme");

        jLabel14.setText("Título:");

        jLabel15.setText("Género:");

        jTextField4.setEditable(false);
        jTextField4.setText("jTextField1");

        jLabel16.setText("Ano:");

        jLabel17.setText("Realizador:");

        jTextField5.setEditable(false);
        jTextField5.setText("jTextField2");

        jLabel18.setText("Produtor:");

        jTextField6.setEditable(false);
        jTextField6.setText("jTextField3");

        jLabel19.setText("IMDB RATING: ");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel22.setText("Resultados:");

        jTextField7.setEditable(false);
        jTextField7.setText("jTextField7");

        jTextField8.setEditable(false);
        jTextField8.setText("jTextField8");

        jTextField9.setEditable(false);
        jTextField9.setText("jTextField9");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));

        jLabel20.setText("CAPA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel20)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel20)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jLabel21.setText("Descrição:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel23.setText("País:");

        jTextField10.setEditable(false);
        jTextField10.setText("jTextField10");

        jButton10.setText("ALUGAR");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel36.setText("Escolher Formato");

        jLabel37.setText("Preço:");

        jTextField19.setEditable(false);
        jTextField19.setText("jTextField18");
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList3);

        javax.swing.GroupLayout jResultadosPanelLayout = new javax.swing.GroupLayout(jResultadosPanel);
        jResultadosPanel.setLayout(jResultadosPanelLayout);
        jResultadosPanelLayout.setHorizontalGroup(
            jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultadosPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                        .addGap(203, 203, 203)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                    .addGroup(jResultadosPanelLayout.createSequentialGroup()
                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAjudaButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                        .addGap(134, 134, 134)
                                        .addComponent(jLabel13))
                                    .addComponent(jLabel22)
                                    .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel21))
                                                .addGap(18, 18, 18)
                                                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(71, 71, 71)
                                                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel18)
                                                            .addComponent(jLabel16)
                                                            .addComponent(jLabel19)))
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel37)
                                                    .addComponent(jLabel36))
                                                .addGap(13, 13, 13)
                                                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel23)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(41, 41, 41)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                                        .addComponent(jVoltarPesquisaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jSairButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addContainerGap(355, Short.MAX_VALUE))))
        );
        jResultadosPanelLayout.setVerticalGroup(
            jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jResultadosPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAjudaButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jResultadosPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addGap(8, 8, 8)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jResultadosPanelLayout.createSequentialGroup()
                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jResultadosPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultadosPanelLayout.createSequentialGroup()
                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel37))
                            .addGroup(jResultadosPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jResultadosPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jResultadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jVoltarPesquisaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSairButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jSairButton4.setText("SAIR");
        jSairButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairButton4ActionPerformed(evt);
            }
        });

        jVoltarButton4.setText("Voltar");
        jVoltarButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarButton4ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel24.setText("Histórico");

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        javax.swing.GroupLayout jHistoricoPanelLayout = new javax.swing.GroupLayout(jHistoricoPanel);
        jHistoricoPanel.setLayout(jHistoricoPanelLayout);
        jHistoricoPanelLayout.setHorizontalGroup(
            jHistoricoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHistoricoPanelLayout.createSequentialGroup()
                .addGroup(jHistoricoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jHistoricoPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jVoltarButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jSairButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jHistoricoPanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel24))
                    .addGroup(jHistoricoPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jHistoricoPanelLayout.setVerticalGroup(
            jHistoricoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHistoricoPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel24)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addGroup(jHistoricoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVoltarButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSairButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLoginPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        jLoginPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        jLoginPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        jLoginButton.setText("Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel5.setText("[NOME DO VIDEOCLUBE]");

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jUsernameField)
                    .addComponent(jPasswordField)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(95, 95, 95)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jSairButton5.setText("SAIR");
        jSairButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairButton5ActionPerformed(evt);
            }
        });

        jAjudaButton5.setText("AJUDA");
        jAjudaButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAjudaButton5ActionPerformed(evt);
            }
        });

        jMenuButton5.setText("Voltar");
        jMenuButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuButton5ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel33.setText("Entregar Filme");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel34.setText("Filme a Entregar:");

        jLabel35.setText("1. Escolha o filme a entregar.");

        jLabel42.setText("2. Método de Pagamento:");

        jRadioButton3.setText("Dinheiro");

        jRadioButton4.setText("Multibanco");

        jLabel43.setText("3. Introduza o dinheiro na máquina (dá troco)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel43)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTextField14.setEditable(false);
        jTextField14.setText("jTextField11");

        jLabel44.setText("Valor a Pagar:");

        jLabel45.setText("3. Introduzir Nº");

        jLabel46.setText("CSS:");

        jLabel47.setText("Nº Cartão:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField16)
                            .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPagarButton.setText("Pagar");
        jPagarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPagarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jEntregaPanelLayout = new javax.swing.GroupLayout(jEntregaPanel);
        jEntregaPanel.setLayout(jEntregaPanelLayout);
        jEntregaPanelLayout.setHorizontalGroup(
            jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEntregaPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jAjudaButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jLabel33)
                .addContainerGap(386, Short.MAX_VALUE))
            .addGroup(jEntregaPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEntregaPanelLayout.createSequentialGroup()
                        .addGroup(jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jEntregaPanelLayout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(262, 262, 262))
                            .addGroup(jEntregaPanelLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton4)
                                    .addGroup(jEntregaPanelLayout.createSequentialGroup()
                                        .addComponent(jRadioButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                        .addComponent(jLabel44)))
                                .addGap(18, 18, 18)))
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel35)
                    .addGroup(jEntregaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(82, 82, 82)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(jEntregaPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jPagarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jMenuButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jSairButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(jEntregaPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jEntregaPanelLayout.setVerticalGroup(
            jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEntregaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAjudaButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGroup(jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jEntregaPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEntregaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addGap(45, 45, 45)))
                .addGap(18, 18, 18)
                .addGroup(jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEntregaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jSairButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jEntregaPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jEntregaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPagarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jMenuButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jSairButton6.setText("SAIR");
        jSairButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairButton6ActionPerformed(evt);
            }
        });

        jVoltarButton6.setText("Voltar");
        jVoltarButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarButton6ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel25.setText("Dados Pessoais");

        jLabel26.setText("Nome:");

        jTextField11.setEditable(false);
        jTextField11.setText("jTextField11");

        jLabel27.setText("Morada:");

        jTextField12.setEditable(false);
        jTextField12.setText("jTextField12");

        jLabel28.setText("E-mail:");

        jTextField13.setEditable(false);
        jTextField13.setText("jTextField13");

        javax.swing.GroupLayout jDadosPanelLayout = new javax.swing.GroupLayout(jDadosPanel);
        jDadosPanel.setLayout(jDadosPanelLayout);
        jDadosPanelLayout.setHorizontalGroup(
            jDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDadosPanelLayout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(jVoltarButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jSairButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jDadosPanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel25)
                .addContainerGap(325, Short.MAX_VALUE))
            .addGroup(jDadosPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDadosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDadosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField12))
                    .addGroup(jDadosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField11)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jDadosPanelLayout.setVerticalGroup(
            jDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDadosPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel25)
                .addGap(50, 50, 50)
                .addGroup(jDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDadosPanelLayout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addGroup(jDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVoltarButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSairButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        mainPanel.setBackground(new java.awt.Color(255, 204, 204));
        mainPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        mainPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Botões _______________Botões___________________Botões__________Botões
     *
     */
    private void jPesquisarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisarButtonActionPerformed
        //Set panel's visibility acordingly
        String [] generos = gerir_users.verListadeGeneros();
        int i;
        DefaultComboBoxModel modeloDados = new DefaultComboBoxModel();
        for(i=0;i<generos.length;i++){
            modeloDados.addElement(generos[i]);
        }
        jComboBox1.setModel(modeloDados);
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(false);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(true);
    }//GEN-LAST:event_jPesquisarButtonActionPerformed

    private void jEntregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEntregarButtonActionPerformed
        //Set panel's visibility acordingly
        String [] requisicoes = gerir_users.verListadeRequisicoes();
        int i;
        DefaultComboBoxModel modeloDados = new DefaultComboBoxModel();
        for(i=0;i<requisicoes.length;i++){
            modeloDados.addElement(requisicoes[i]);
        }
        jComboBox4.setModel(modeloDados);
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(true);
        jLoginPanel.setVisible(false);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jEntregarButtonActionPerformed

    private void jHistoricoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHistoricoButtonActionPerformed
        //Set panel's visibility acordingly
        String[] historico = gerir_users.verHistorico();
        DefaultListModel modeloDados = new DefaultListModel();
        int i;

        for(i=0;i<historico.length;i++){
            modeloDados.addElement(historico[i]);
        }
        jList2.setModel(modeloDados);
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(false);
        jHistoricoPanel.setVisible(true);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jHistoricoButtonActionPerformed

    private void jDadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDadosButtonActionPerformed
        //Set panel's visibility acordingly
        
        jDadosPanel.setVisible(true);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(false);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jDadosButtonActionPerformed

    private void jAjudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAjudaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAjudaButtonActionPerformed

    private void jAjudaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAjudaButton2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jAjudaButton2ActionPerformed

    private void jAjudaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAjudaButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAjudaButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        // Botão Alugar na frame esultados de pesquisa, pega no ID e formato do video.
        Component frame = new Component() {};
        try{
            System.out.println("ola "+jList1.getSelectedValue().toString());
            String verifica_aluguer=gerir_users.alugar(jList1.getSelectedValue().toString(), jComboBox3.getSelectedItem().toString());
            if(verifica_aluguer==null){
                JOptionPane.showMessageDialog(frame,
                    "Aluguer sem sucesso",
                    "Aviso!",
                    JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(frame,
                    "Aluguer com sucesso",
                    "Obrigado!",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(frame,
                    "Tem de seleccionar um filme",
                    "Aviso!",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton10ActionPerformed


    private void jAjudaButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAjudaButton5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jAjudaButton5ActionPerformed

    private void jSairButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairButton3ActionPerformed
        // TODO: Invalidar a sessão
        //Set panel's visibility acordingly
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(true);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jSairButton3ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jSairButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairButton6ActionPerformed
        // TODO: Invalidar a sessão
        //Set panel's visibility
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(true);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jSairButton6ActionPerformed

    private void jSairButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairButton5ActionPerformed
        // TODO: Invalidar a sessão
        //Set panel's visibility
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(true);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jSairButton5ActionPerformed

    private void jSairButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairButton4ActionPerformed
        // TODO: Invalidar a sessão
        //Set panel's visibility
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(true);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jSairButton4ActionPerformed

    private void jSairButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairButton2ActionPerformed
        // TODO: Invalidar a sessão
        //Set panel's visibility
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(true);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jSairButton2ActionPerformed

    private void jSairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairButtonActionPerformed
        // TODO: Invalidar a sessão
        //Set panel's visibility
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(true);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jSairButtonActionPerformed

    private void jVoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarButtonActionPerformed
        //Set panel's visibility
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(false);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(true);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jVoltarButtonActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        // TODO: reunir dados para fazer a mega query e fazê-la . reset variáveis de pesquisa?
        //Set panel's visibility
        // String[] generos
        //String [] filmesPesquisados = gestorFilmes.procuraFilmes(jTextField3.getText(),jSpinner3.getValue().toString(),jSpinner4.getValue().toString(),
          //      ,jTextField2.getText(),jSpinner1.getValue().toString(),jSpinner2.getValue().toString(),
            //    ,jTextField17.getText(),jTextField1.getText(),jComboBox1.getSelectedItem().toString());
        DefaultListModel modeloDados = new DefaultListModel();
        int i;
        for(i=0;i<filmesPesquisados.length;i++){
            modeloDados.addElement(filmesPesquisados[i]);
        }
        jList1.setModel(modeloDados);
        jList1.addListSelectionListener((ListSelectionListener) new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent evento) {
            if (evento.getValueIsAdjusting())
            //ainda selecionando
            return;
            JList list = (JList)evento.getSource();
            if (list.isSelectionEmpty()) {
                    System.out.println("nenhuma seleção");
            } else {
                String idMovie=((String)jList1.getSelectedValue()).split(" ")[0];
                String[] f = gestorFilmes.getFilme(idMovie);
                int i=0;
                jTextField4.setText(f[i++]);
                jTextField7.setText(f[i++]);
                jTextField5.setText(f[i++]);
                jTextField9.setText(f[i++]);
                jTextField10.setText(f[i++]);
                jTextField6.setText(f[i++]);
                jTextArea1.setText(f[i++]);
                jLabel20.setIcon(new ImageIcon(f[i++]));
                jList3.setModel(new OurListModel(Utils.extract(f, i+1)));

            }
        }});
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(false);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(true);
        jPesquisarPanel.setVisible(false);

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jVoltarPesquisaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarPesquisaButtonActionPerformed
        // TODO : reset variaveis de presquisa!
        //Set panel's visibility
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(false);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(true);
    }//GEN-LAST:event_jVoltarPesquisaButtonActionPerformed

    private void jVoltarButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarButton4ActionPerformed
        //Set panel's visibility
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(false);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(true);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jVoltarButton4ActionPerformed

    private void jMenuButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuButton5ActionPerformed
        //Set panel's visibility
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(false);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(true);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jMenuButton5ActionPerformed

    private void jPagarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagarButtonActionPerformed
        // TODO: Processar o pedido
        //Set panel's visibility
        String modo_pagamento;
        Component frame = new Component(){};
        try{
            if(jRadioButton3.isSelected()){
                modo_pagamento="dinheiro";
            }else{
                modo_pagamento="multibanco";
            }
            String numero_cartao=jTextField12.getText();
            String numero_css=jTextField13.getText();
            gerir_users.entregar(jComboBox4.getSelectedItem().toString());

        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(frame,
                "Dados de login incorrectos",
                "Aviso!",
                JOptionPane.WARNING_MESSAGE);
        }
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(true);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(false);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(false);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jPagarButtonActionPerformed

    private void jVoltarButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarButton6ActionPerformed
        //Set panel's visibility
        jDadosPanel.setVisible(false);
        jPanel3.setVisible(false);
        jEntregaPanel.setVisible(false);
        jLoginPanel.setVisible(false);
        jHistoricoPanel.setVisible(false);
        jMenuPanel.setVisible(true);
        jResultadosPanel.setVisible(false);
        jPesquisarPanel.setVisible(false);
    }//GEN-LAST:event_jVoltarButton6ActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // TODO logar o user!!!
        System.out.println("user: "+jUsernameField.getText()+" pass:"+jPasswordField.getText());
        String verificar_login = gerir_users.login(jUsernameField.getText(),jPasswordField.getText());
        System.out.println("resposta: "+verificar_login);
        Component frame = new Component() {};
        if(verificar_login==null){
            /*jDadosPanel.setVisible(false);
            jPanel3.setVisible(false);
            jEntregaPanel.setVisible(false);
            jLoginPanel.setVisible(false);
            jHistoricoPanel.setVisible(false);
            jMenuPanel.setVisible(true);
            jResultadosPanel.setVisible(false);
            jPesquisarPanel.setVisible(false);
            */JOptionPane.showMessageDialog(frame,
            "Dados de login incorrectos",
            "Aviso!",
            JOptionPane.WARNING_MESSAGE);

        }else{
            jUsernameField.setText("");
            jPasswordField.setText("");
            
            jDadosPanel.setVisible(false);
            jPanel3.setVisible(false);
            jEntregaPanel.setVisible(false);
            jLoginPanel.setVisible(false);
            jHistoricoPanel.setVisible(false);
            jMenuPanel.setVisible(true);
            jResultadosPanel.setVisible(false);
            jPesquisarPanel.setVisible(false);

            String[] dados = gerir_users.verDadosPessoais();
            jTextField11.setText(dados[0]);
            jTextField12.setText(dados[1]);
            jTextField13.setText(dados[2]);
        }
    }//GEN-LAST:event_jLoginButtonActionPerformed
/*
     * Botões _______________Botões___________________Botões__________Botões
     *
     */
    

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAjudaButton;
    private javax.swing.JButton jAjudaButton2;
    private javax.swing.JButton jAjudaButton3;
    private javax.swing.JButton jAjudaButton5;
    private javax.swing.JButton jButton10;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JToggleButton jDadosButton;
    private javax.swing.JPanel jDadosPanel;
    private javax.swing.JPanel jEntregaPanel;
    private javax.swing.JToggleButton jEntregarButton;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JToggleButton jHistoricoButton;
    private javax.swing.JPanel jHistoricoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JButton jMenuButton5;
    private javax.swing.JPanel jMenuPanel;
    private javax.swing.JButton jPagarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JToggleButton jPesquisarButton;
    private javax.swing.JPanel jPesquisarPanel;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JPanel jResultadosPanel;
    private javax.swing.JButton jSairButton;
    private javax.swing.JButton jSairButton2;
    private javax.swing.JButton jSairButton3;
    private javax.swing.JButton jSairButton4;
    private javax.swing.JButton jSairButton5;
    private javax.swing.JButton jSairButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jSearchButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jUsernameField;
    private javax.swing.JButton jVoltarButton;
    private javax.swing.JButton jVoltarButton4;
    private javax.swing.JButton jVoltarButton6;
    private javax.swing.JButton jVoltarPesquisaButton;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
